#Chris West, cgw29

CC     = gcc
CFLAGS= -std=c99 -pedantic -Wall -I/c/cs323/Hwk2/
HWK    = /c/cs323/Hwk2

parsley: parsley.o  ${HWK}/mainParsley.o
	${CC} ${CFLAGS} -o parsley parsley.o ${HWK}/mainParsley.o